# Generated by Django 2.1.7 on 2019-02-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190225_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(max_length=120)),
                ('dashboard_description', models.TextField()),
                ('dashboard_date', models.DateField()),
                ('dashboard_img', models.ImageField(upload_to='')),
                ('dashboard_location', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='events.Event'),
        ),
    ]
