# Generated by Django 2.1.7 on 2019-02-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190226_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
